# Use to build modules

.PHONY: test clean

all:
	@echo Targets: all test gen genone


gen:
	@python3 genkeyman.py

genone:
	@python3 genkey.py

test:
	@make -C client test


clean:
	@rm -rf ../data/keys

md5:













