
all:
	@echo Targets: test tests

tests:
	cd tests ; pytest

test:
	./testwrapper.py
	./testwrapper2.py
	./testwrapper3.py
	./testwrapper4.py
	./testhash.py
	./testlink.py
	./testpow.py
	./testpayld.py
	./testdump.py

